#!/usr/bin/env bash
# Regenerates the synthetic golden fixtures (docs/design.md §18) with FFmpeg ≥ 6.0.
# Encoders aren't bit-exact across FFmpeg versions, so the committed files are the source of
# truth and their expected properties live in crates/media/tests/fixtures.rs (Day 49); rerun
# this only to replace a fixture on purpose. The real_* files are MediaRecorder output captured
# from the recorder (see README.md here) and can't be regenerated by this script.
set -euo pipefail
cd "$(dirname "$0")"
ff() { ffmpeg -hide_banner -loglevel error -y "$@"; }

# Like Chrome's MediaRecorder: VP9/Opus WebM written as a live stream (no duration, no cues).
ff -f lavfi -i "testsrc2=size=640x360:rate=30:duration=30" -f lavfi -i "sine=frequency=440:duration=30" \
  -c:v libvpx-vp9 -deadline realtime -cpu-used 8 -b:v 250k -g 60 -c:a libopus -b:a 48k \
  -f webm -live 1 vp9_opus_30s.webm

# Pause/resume as a timestamp gap: 5 s, then a 3 s jump, then 5 s more (VP8/Opus, live WebM).
ff -f lavfi -i "testsrc2=size=640x360:rate=30:duration=10" -f lavfi -i "sine=frequency=330:duration=10" \
  -vf "setpts='if(gte(T,5),PTS+3/TB,PTS)'" -af "asetpts='if(gte(T,5),PTS+3/TB,PTS)'" \
  -c:v libvpx -deadline realtime -cpu-used 8 -b:v 300k -c:a libopus -b:a 48k \
  -f webm -live 1 vp8_opus_paused.webm

# Like Safari's MediaRecorder: fragmented MP4, H.264/AAC (the remux-only path).
ff -f lavfi -i "testsrc2=size=640x360:rate=30:duration=20" -f lavfi -i "sine=frequency=550:duration=20" \
  -c:v libx264 -profile:v baseline -preset veryfast -b:v 400k -g 60 -pix_fmt yuv420p \
  -c:a aac -b:a 64k -movflags frag_keyframe+empty_moov+default_base_moof h264_aac_safari_20s.mp4

# A silent recording: VP9 only.
ff -f lavfi -i "testsrc2=size=640x360:rate=30:duration=10" \
  -c:v libvpx-vp9 -deadline realtime -cpu-used 8 -b:v 250k -g 60 -f webm -live 1 vp9_no_audio.webm

# A crash mid-chunk: a 10 s take whose last cluster is cut off part way.
ff -f lavfi -i "testsrc2=size=640x360:rate=30:duration=10" -f lavfi -i "sine=frequency=440:duration=10" \
  -c:v libvpx-vp9 -deadline realtime -cpu-used 8 -b:v 250k -g 60 -c:a libopus -b:a 48k \
  -f webm -live 1 truncated.tmp.webm
size=$(stat -c %s truncated.tmp.webm)
head -c $((size * 9 / 10)) truncated.tmp.webm > truncated_last_chunk.webm
rm truncated.tmp.webm

# Bytes that only claim to be a video.
printf 'This is not a video. It only has a .webm name.\n%.0s' $(seq 1 64) > not_a_video.webm

ls -l *.webm *.mp4
