/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Idempotent and keyed off the refresh cookie (see `IdentityService::logout`): logging out with
         *     no cookie, an already-revoked cookie, or a garbage cookie all just clear client cookies and
         *     return `204`, matching the anti-enumeration style used elsewhere in this module. Also acts on
         *     an ambient cookie, so it needs the CSRF double-submit check too.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * "Log out everywhere": revokes every refresh session for the caller and clears this
         *     browser's cookies. Needs a live session (it acts on the user, not one refresh token) and
         *     the CSRF check. Other devices' access cookies lapse within `ACCESS_TOKEN_TTL` (15 min).
         */
        post: operations["logout_all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Always `202` with the same message, whether or not the email exists (US-03) -- the identity
         *     service already enforces this at the service layer, this handler just can't turn it into a
         *     non-generic error either.
         */
        post: operations["forgot_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reset_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Keys off the refresh cookie, not `SessionClaims` -- a still-valid refresh token should be
         *     usable to get a new access cookie even after the old access cookie has already expired,
         *     which is the whole point of having a separate, longer-lived refresh token (US-02). Acts
         *     purely on an ambient cookie, so it's one of the two routes that need the CSRF double-submit
         *     check (see `crate::csrf`).
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verify_email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Composes the user (from `identity`) with their memberships (from `tenancy`). `Session`
         *     access, not `Workspace`: it lists the caller's own memberships, not one workspace's data.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Profile settings. Acts on the ambient session cookie, so it takes the CSRF double-submit
         *     check like `/auth/refresh` and `/auth/logout`.
         */
        patch: operations["update_me"];
        trace?: never;
    };
    "/api/v1/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Starts a recording: creates the recording and its first take in the caller's current
         *     workspace (upload protocol v1, docs/design.md §9). Chunks are presigned and acked against
         *     the returned `take_id`.
         */
        post: operations["create_recording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/takes/{take_id}/chunks/{idx}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirms chunk `idx` is uploaded, with its size and SHA-256. Idempotent on
         *     `(take_id, idx)`: the same size and hash again is a no-op; a different one is `409`.
         */
        post: operations["ack_chunk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/takes/{take_id}/chunks/{idx}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Presigned `PUT` URLs for chunk `idx` (and, with `?count=`, the chunks after it). Only the
         *     recording's owner gets them, and only until the take is finalized. The browser then `PUT`s
         *     the bytes straight to object storage (media never passes through the API).
         */
        post: operations["presign_chunks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/takes/{take_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Declares the take complete. When every chunk `0..chunk_count` is acknowledged the take is
         *     finalized, the recording moves to `processing` and `TakeFinalized` is emitted; otherwise
         *     `422` lists the missing indexes. Retrying a successful finalize is `202` again.
         */
        post: operations["finalize_take"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/takes/{take_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Which chunks the server has acknowledged, so an interrupted or recovered upload sends only
         *     the missing ones. Owner only.
         */
        get: operations["take_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AckChunkBody: {
            /** @description SHA-256 of the chunk's bytes, 64 hex characters. */
            sha256: string;
            /**
             * Format: int64
             * @description Bytes PUT for this chunk (1 to 16 MiB). Must match the stored object.
             */
            size_bytes: number;
        };
        AckChunkResponse: {
            /** Format: int32 */
            idx: number;
            status: components["schemas"]["AckStatus"];
        };
        /** @enum {string} */
        AckStatus: "acked" | "already_acked";
        ChunkUploadUrl: {
            /** Format: int32 */
            idx: number;
            /** @description Presigned `PUT` for this chunk's bytes. A bearer credential: don't log it. */
            url: string;
        };
        CreateRecordingBody: {
            has_camera: boolean;
            has_mic: boolean;
            has_system_audio: boolean;
            /**
             * @description The take's MIME type as `MediaRecorder` reports it, e.g. `video/webm;codecs=vp9,opus`.
             *     The container must be `video/webm` or `video/mp4`.
             */
            mime_type: string;
            /** @description Optional; blank or missing becomes "Untitled recording". At most 200 characters. */
            title?: string | null;
        };
        CreateRecordingResponse: {
            /**
             * Format: int32
             * @description The longest take the workspace's plan accepts (pauses excluded). The recorder stops by
             *     itself before this; finalize rejects anything longer.
             */
            max_duration_ms: number;
            /** Format: uuid */
            recording_id: string;
            /** Format: uuid */
            take_id: string;
        };
        FinalizeBody: {
            /**
             * Format: int32
             * @description Number of chunks in the take; indexes `0..chunk_count` must all be acknowledged.
             */
            chunk_count: number;
            /**
             * Format: int32
             * @description The take's length, pauses excluded.
             */
            duration_ms: number;
        };
        FinalizeResponse: {
            /** Format: uuid */
            recording_id: string;
            state: components["schemas"]["RecordingStateName"];
        };
        ForgotPasswordBody: {
            email: string;
        };
        LoginBody: {
            email: string;
            password: string;
        };
        MeResponse: {
            /**
             * Format: uuid
             * @description The workspace the session's access cookie was issued for -- lets the client pick the
             *     right entry out of `workspaces` as "current" without guessing.
             */
            current_workspace_id: string;
            user: components["schemas"]["MeUser"];
            workspaces: components["schemas"]["MeWorkspace"][];
        };
        MeUser: {
            display_name: string;
            email: string;
            email_verified: boolean;
            /** Format: uuid */
            id: string;
        };
        MeWorkspace: {
            /** Format: uuid */
            id: string;
            is_personal: boolean;
            name: string;
            role: components["schemas"]["MemberRole"];
        };
        /**
         * @description Mirrors `kernel::Role` for the OpenAPI schema (kernel stays free of API concerns).
         * @enum {string}
         */
        MemberRole: "owner" | "admin" | "member" | "viewer";
        /** @description The body of every endpoint that only reports an outcome. */
        MessageResponse: {
            message: string;
        };
        /** @description The `422` body when chunks are missing: problem details plus the indexes to upload. */
        MissingChunksProblem: {
            detail: string;
            /** @description Missing indexes, ascending; at most 1000 listed. */
            missing: number[];
            /** @description How many are missing in total. */
            missing_count: number;
            /** Format: int32 */
            status: number;
            title: string;
            type: string;
        };
        PresignChunksResponse: {
            /**
             * Format: int64
             * @description Seconds each URL stays valid.
             */
            expires_in_s: number;
            urls: components["schemas"]["ChunkUploadUrl"][];
        };
        /** @description RFC 9457 problem details, the body of every error response. */
        Problem: {
            detail: string;
            /** Format: int32 */
            status: number;
            title: string;
            type: string;
        };
        ReceivedChunkBody: {
            /** Format: int32 */
            idx: number;
            /** @description Lowercase hex. */
            sha256: string;
            /** Format: int32 */
            size_bytes: number;
        };
        /** @enum {string} */
        RecordingStateName: "processing";
        RegisterBody: {
            display_name: string;
            email: string;
            password: string;
        };
        ResetPasswordBody: {
            password: string;
            token: string;
        };
        TakeStatusResponse: {
            /** @description The acknowledged chunks with the size and SHA-256 recorded for each. */
            chunks: components["schemas"]["ReceivedChunkBody"][];
            finalized: boolean;
            /** @description Acknowledged chunk indexes, ascending. Upload the rest. */
            received: number[];
            /** Format: uuid */
            recording_id: string;
            /** Format: uuid */
            take_id: string;
        };
        UpdateProfileBody: {
            display_name: string;
        };
        VerifyEmailBody: {
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Logged in; sets session, refresh and CSRF cookies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Login rate limit hit */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked (idempotent); cookies cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or mismatched CSRF token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every session revoked; cookies cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing or mismatched CSRF token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    forgot_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordBody"];
            };
        };
        responses: {
            /** @description Same response whether or not the email exists */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    reset_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordBody"];
            };
        };
        responses: {
            /** @description Password changed; all sessions revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Invalid or expired reset token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Password too weak */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotated; sets new session, refresh and CSRF cookies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Missing, invalid or reused refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing or mismatched CSRF token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterBody"];
            };
        };
        responses: {
            /** @description Accepted; a verification email is sent if the details are valid */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Invalid email, password or display name */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Signup rate limit hit */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    verify_email: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailBody"];
            };
        };
        responses: {
            /** @description Email verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Invalid or expired verification token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user and their workspaces */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileBody"];
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeUser"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing or mismatched CSRF token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid display name */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_recording: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecordingBody"];
            };
        };
        responses: {
            /** @description Recording and take created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRecordingResponse"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The plan's recording limit is reached (free tier: 50) */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing CSRF token, or the role can't create recordings */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not a member of the session's workspace */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid title or MIME type */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    ack_chunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The take */
                take_id: string;
                /** @description Chunk index (0-based) */
                idx: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AckChunkBody"];
            };
        };
        responses: {
            /** @description Chunk recorded (or already recorded identically) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckChunkResponse"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing or mismatched CSRF token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such take, or not the caller's */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Acked before with a different hash or size, or the take is finalized */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not uploaded, size differs from storage, or invalid size/hash/index */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    presign_chunks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The take */
                take_id: string;
                /** @description First chunk index (0-based) */
                idx: number;
                /**
                 * @description How many consecutive chunk URLs to return, starting at `idx` (1–10, default 1). Used to
                 *     batch round trips after a reconnect.
                 */
                count: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload URLs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignChunksResponse"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing or mismatched CSRF token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such take, or not the caller's */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The take is already finalized */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description count outside 1–10 or index too large */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    finalize_take: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The take */
                take_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalizeBody"];
            };
        };
        responses: {
            /** @description Finalized; processing starts */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizeResponse"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Longer than the plan allows (free tier: 10 minutes) */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Missing or mismatched CSRF token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such take, or not the caller's */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Finalized before with another count, or the recording no longer accepts uploads */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Chunks missing (listed in `missing`), extra chunks, or invalid count/duration */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["MissingChunksProblem"];
                };
            };
        };
    };
    take_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The take */
                take_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload state of the take */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TakeStatusResponse"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No such take, or not the caller's */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liveness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Readiness: the database answers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database unavailable */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
