//! Test doubles shared by media's tests.

use std::collections::HashMap;
use std::path::Path;
use std::sync::Mutex;
use std::time::Duration;

use platform::{ObjectMeta, ObjectReader, ObjectStore, StorageError};
use url::Url;

/// An in-memory object store.
#[derive(Default)]
pub struct MemoryStore {
    objects: Mutex<HashMap<String, (Vec<u8>, String)>>,
}

impl MemoryStore {
    pub fn insert(&self, key: &str, bytes: Vec<u8>) {
        self.objects.lock().expect("lock").insert(
            key.to_string(),
            (bytes, "application/octet-stream".to_string()),
        );
    }

    pub fn bytes(&self, key: &str) -> Option<Vec<u8>> {
        self.objects
            .lock()
            .expect("lock")
            .get(key)
            .map(|(bytes, _)| bytes.clone())
    }

    pub fn content_type(&self, key: &str) -> Option<String> {
        self.objects
            .lock()
            .expect("lock")
            .get(key)
            .map(|(_, content_type)| content_type.clone())
    }
}

#[async_trait::async_trait]
impl ObjectStore for MemoryStore {
    async fn presign_put(&self, _key: &str, _ttl: Duration) -> Result<Url, StorageError> {
        Err(StorageError::Request("not used by media".to_string()))
    }
    async fn presign_get(&self, _key: &str, _ttl: Duration) -> Result<Url, StorageError> {
        Err(StorageError::Request("not used by media".to_string()))
    }
    async fn head(&self, key: &str) -> Result<Option<ObjectMeta>, StorageError> {
        Ok(self
            .objects
            .lock()
            .expect("lock")
            .get(key)
            .map(|(bytes, content_type)| ObjectMeta {
                size: bytes.len() as u64,
                content_type: Some(content_type.clone()),
            }))
    }
    async fn delete_prefix(&self, prefix: &str) -> Result<u64, StorageError> {
        let mut objects = self.objects.lock().expect("lock");
        let before = objects.len();
        objects.retain(|key, _| !key.starts_with(prefix));
        Ok((before - objects.len()) as u64)
    }
    async fn get(&self, key: &str) -> Result<Option<ObjectReader>, StorageError> {
        Ok(self.bytes(key).map(|bytes| {
            let reader: ObjectReader = Box::pin(std::io::Cursor::new(bytes));
            reader
        }))
    }
    async fn put_file(
        &self,
        key: &str,
        path: &Path,
        content_type: &str,
    ) -> Result<u64, StorageError> {
        let bytes = tokio::fs::read(path)
            .await
            .map_err(|error| StorageError::Request(error.to_string()))?;
        let size = bytes.len() as u64;
        self.objects
            .lock()
            .expect("lock")
            .insert(key.to_string(), (bytes, content_type.to_string()));
        Ok(size)
    }
}

impl MemoryStore {
    pub fn remove(&self, key: &str) {
        self.objects.lock().expect("lock").remove(key);
    }
}

pub fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    crate::domain::to_hex(&Sha256::digest(bytes))
}

/// Whether tests that need FFmpeg run. CI sets `MEDIA_REQUIRE_FFMPEG=1`, so a missing FFmpeg
/// fails there instead of silently skipping.
pub async fn ffmpeg_available() -> bool {
    let found = tokio::process::Command::new("ffmpeg")
        .arg("-version")
        .output()
        .await
        .map(|output| output.status.success())
        .unwrap_or(false);
    assert!(
        found || std::env::var_os("MEDIA_REQUIRE_FFMPEG").is_none(),
        "MEDIA_REQUIRE_FFMPEG is set but ffmpeg isn't on PATH"
    );
    found
}

/// A VP8/Opus WebM of `seconds`, 640x360, generated by FFmpeg into the temp dir; `None` if
/// FFmpeg isn't installed.
pub async fn generated_webm(seconds: u32) -> Option<std::path::PathBuf> {
    if !ffmpeg_available().await {
        return None;
    }
    let path = std::env::temp_dir().join(format!("sintade-gen-{}.webm", uuid::Uuid::now_v7()));
    let status = tokio::process::Command::new("ffmpeg")
        .args(["-v", "error", "-y", "-f", "lavfi", "-i"])
        .arg(format!("testsrc2=size=640x360:rate=30:duration={seconds}"))
        .args(["-f", "lavfi", "-i"])
        .arg(format!("sine=frequency=440:duration={seconds}"))
        .args([
            "-c:v",
            "libvpx",
            "-deadline",
            "realtime",
            "-b:v",
            "500k",
            "-c:a",
            "libopus",
        ])
        .arg(&path)
        .status()
        .await
        .expect("run ffmpeg");
    assert!(status.success(), "ffmpeg generated the WebM");
    Some(path)
}

/// Whether FFmpeg decodes every frame of `path` without an error.
pub async fn decodes_fully(path: &Path) -> bool {
    let output = tokio::process::Command::new("ffmpeg")
        .args(["-v", "error", "-xerror", "-i"])
        .arg(path)
        .args(["-f", "null", "-"])
        .output()
        .await
        .expect("run ffmpeg");
    output.status.success() && output.stderr.is_empty()
}

/// A golden fixture from `docs/fixtures/` (docs/design.md §18).
pub fn fixture_path(name: &str) -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../docs/fixtures")
        .join(name)
}

pub async fn fixture(name: &str) -> Vec<u8> {
    tokio::fs::read(fixture_path(name))
        .await
        .unwrap_or_else(|error| panic!("fixture {name}: {error}"))
}
