[package]
name = "platform"
version = "0.1.0"
edition.workspace = true

[lib]
name = "platform"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.92"
aws-sdk-s3 = "1.149.0"
kernel = { version = "0.1.0", path = "../kernel" }
lettre = { version = "0.11.23", default-features = false, features = ["tokio1-rustls-tls", "smtp-transport", "builder"] }
rand = "0.10.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sqlx = { version = "0.9.0", features = ["postgres", "runtime-tokio", "tls-rustls", "uuid"] }
thiserror = "2.0.20"
time = "0.3.55"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
url = "2.5.8"
uuid = { version = "1.26.1", features = ["v7"] }

[dev-dependencies]
reqwest = { version = "0.13.5", default-features = false, features = ["json", "rustls"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
